### ISSUE TITLE
请教大神

### ISSUE THREAD

**Issue by sytuzhouyong** [wayone/Indicator#1]
打扰了兄弟，麻烦问下CircleIndicatorView类中 setDataThatIsRelatedToFrameToCustomRatio方法里的168.5这个参数是什么意思？以及 calculateFourKeyPointForRectangleWithCircleCenter 这个方法的逻辑是什么？哎 数学不太好，还请答疑下

**Comment by wayone** [comment]
168.5 / 294 这个就是一个比例值，这两个数字都是我的设计稿上的具体值，就是长度 A 比上长度 B，得到一个比例值。至于 168.5 指的是哪个长度，你修改这个值，对比一下效果就知道了。

calculateFourKeyPointForRectangleWithCircleCenter。这个方法的逻辑，你参照我给的那几个参数，画个图，尝试自己计算一下，就大概知道了。

**Comment by sytuzhouyong** [comment]
ok，非常感谢
